# Works best with 120x40 terminal window
# Generated ASCII with https://www.text-image.com/convert/ascii.html

echo -e '\0033\0143'
echo '\e[31m                                                        `...--...`                                                  '
echo '\e[31m                                                  `.:oydmmmNNNNmmmdyo:.`                                            '
echo '\e[31m                                               `:sdNMMNmdhyhhhhyhdmNMMNds:`                                         '
echo '\e[31m                                             -omMMNho:../ydmNNmdy/..:ohNMMdo.                                       '
echo '\e[31m                                           .sNMNh+.   .hMMMMMMMMMMh.   .+hNMNs.                                     '
echo '\e[31m                                         `+NMNh:     `mMMMMMMMMMMMMm`     :hNMN+`                                   '
echo '\e[31m                                        `yMMm/       :MMMMMMMMMMMMMM:       /mMMy`                                  '
echo '\e[31m                                       `dMMh.  ````  .NMMMMMMMMMMMMN.  ````  .hMMd`                                 '
echo '\e[31m                                       hMMh`.ohdmmdho-+NMMMMMMMMMMN+-ohdmmdho.`hMMh                                 '
echo '\e[31m                                      /MMN-sNMMMMMMMMMh/smNMMMMNms/hMMMMMMMMMNs-NMM/                                '
echo '\e[31m                                      dMMohMMMMMMMMMMMMm``-mMMm-``mMMMMMMMMMMMMhoMMd                                '
echo '\e[31m                                     .MMM:MMMMMMMMMMMMMM/  dMMd  /MMMMMMMMMMMMMM/MMM.                               '
echo '\e[31m                                     -MMM.NMMMMMMMMMMMMM-  dMMd  -MMMMMMMMMMMMMN.MMM-                               '
echo '\e[31m                                     -MMM`/NMMMMMMMMMMMh`  dMMd  `hMMMMMMMMMMMN/`MMM-                               '
echo '\e[31m                                     `NMM/ -yNMMMMMMNMMMh: dMMd :hMMMNMMMMMMNy- /MMN                                '
echo '\e[31m                                      sMMd   `-/+++:`/dMMMhmMMNhMMMd:`:+++/-`   dMMs                                '
echo '\e[31m                                      `NMM+            /dMMMMMMMMd/            +MMN`                                '
echo '\e[31m                                       :MMM+             /dMMMMd/             +MMM:                                 '
echo '\e[31m                                        :NMMs`             mMMm             `sMMN:                                  '
echo '\e[31m                                         -dMMm/            dMMd            /mMMd-                                   '
echo '\e[31m                                          `oNMMd/`         dMMd         `/dMMNo`                                    '
echo '\e[31m                                            `omMMNy/.      dMMd      ./yNMMmo`                                      '
echo '\e[31m                                              `/yNMMNmho+::yhhy::+ohmNMMNy/`                                        '
echo '\e[31m                                                 `-oymNMMMNNNNNNMMMNmyo-`                                           '
echo '\e[31m                                                     ``-:/+oooo+/:-``                                               '
echo '                                                                                                                          '
echo '\e[90m        `-+osyyyo.   -yyyyyyyyyyyyys+.    ./osyyys-          .yyyys:      `-/osyyyo.   /yyy-   .+yyyyso++syyyy+`    '
echo '\e[90m      `+dNMMMMMMMmo. :MMMMMMMMMMMMMMMm` /hNMMMMMMMNy-        -MMMMMNd/  `+dNMMMMMMMmo. yMMM:.+hNMMMmhdNNMMMMMMMm+`  '
echo '\e[90m     .dMMMho/:/hMMMmo:MMMd///////+mMMM-yMMMds/::yNMMNy.-+oooosdsoooo++ .hMMMdo/:/hMMMmoyMMMmNMMMmy::mMMNho/:/hMMMm+ '
echo '\e[90m     yMMM+`    `:NMMM/MMMh`       ohhhsMMMy`     -dMMM: ./hNMMMmy:`    yMMM+`    `:NMMMyMMMMMmy:`  dMMM:     `/MMMm '
echo '\e[90m     mMMM.       NMMM:NMMMms:`        sMMM+       yMMM:----.+hNMMMms:` dMMM-       mMMMsNMMMMs-`   NMMN`       MMMm '
echo '\e[90m     +MMMd:.`    NMMM-dMMMMMMms:`     -NMMm+.`    yMMM:NMMN.``-odMMMMmssMMMd/.`    mMMMomMMMMMNdo-`sMMMh:.`    MMMm '
echo '\e[90m      +mMMMmdddy.NMMM-hhho+dNMMMds:`   :dMMMNmddh:yMMM:mMMMmddddmMMMMMMs+mMMMmdddy.mMMMohhh+sdMMMNdohNMMMmddds.MMMm '
echo '\e[90m       .+hmNNNNNomNNN       -+dNNNNho.  `/ydmNNNNhsNNN::dNNNNNNNNNNNNNNo .+hmmNNNNodNNN`     `:smNNNmmdmmNNNNN/NNNd '
echo '\e[90m                                                                                                                    '
